# Generated by Django 6.0 on 2025-12-31 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Opcion',  
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Pregunta',
        ),
    ]
